FROM 		aarif8/httpd

MAINTAINER 	aarif@ilg.cat

RUN		yum update -y
RUN		rpm -Uvh --replacepkgs https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN		rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

RUN 		yum -y install php72w php72w-bcmath php72w-cli php72w-common php72w-gd php72w-intl php72w-ldap php72w-mbstring php72w-mysql php72w-pear php72w-soap php72w-xml php72w-xmlrpc

RUN		yum clean all && rm -rf /tmp/yum*

EXPOSE 80

CMD ["/usr/sbin/httpd","-D","FOREGROUND"]
